version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
     - 2181:2181
  admin:
    image: htynkn/dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - 8080
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181
  user-manage-server:
    image: htynkn/dubbo-demo-user-manage-server
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181

