version: '3'

services:
  zookeeper:
    image: zookeeper
  admin:
    image: htynkn/dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - 7001
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181