version: '3'

services:
  zookeeper:
    image: zookeeper
  admin:
    image: htynkn/dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - 8080
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181
  provider:
    image: bolingcavalry/dubbo_provider_tomcat:0.0.1
    links:
      - "zookeeper:zkhost"
