version: '3'

services:
  zookeeper:
    image: zookeeper
  admin:
    image: htynkn/dubbo-registry-simple
    depends_on:
      - zookeeper
    ports:
      - 8080
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181