version: '3'

services:
  database:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=0
      - MYSQL_DATABASE=cat
  cat:
    image: htynkn/dianping-cat
    depends_on:
      - database
    ports:
      - 8080
    environment:
      - DATABASE_USER=root
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=0
